#define	LSOF_BLDCMT	""
#define	LSOF_CC		"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-gcc-4.2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -miphoneos-version-min=4.0"
#define	LSOF_CCV	"4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.1.00)"
#define	LSOF_CCDATE	"Sun Apr 29 15:02:57 MSK 2012"
#define	LSOF_CCFLAGS	"-D__arm__ -arch armv6 -arch armv7 -DHASIPv6 -mdynamic-no-pic -DHASUTMPX -DDARWINV=900 -DHAS_STRFTIME -DLSOF_VSTR=\"11.3.0\" -O"
#define  LSOF_CINFO      "libproc-based"
#define	LSOF_HOST	"omac.local"
#define	LSOF_LDFLAGS	"-L./lib -llsof -lcurses -lproc"
#define	LSOF_LOGNAME	"oleglevchenko"
#define	LSOF_SYSINFO	"Darwin omac.local 11.3.0 Darwin Kernel Version 11.3.0: Thu Jan 12 18:47:41 PST 2012; root:xnu-1699.24.23~1/RELEASE_X86_64 x86_64"
#define	LSOF_USER	"oleglevchenko"
#define	LSOF_VERSION	"4.82"
